platform:
  security:
    jwt:
      issuer: kidzSchool
      expiration: 30 #minutes
      secretKey: your256bitsecretkeyyour256bitsecretkey

platform2:
  tokens:
    jwt:
      expiration: 60 #minutes
      secretKey: yoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkey

springdoc:
  packages-to-scan: com.example.todorest.endpoint